apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonveil-backend-dev
  labels:
    k8s-app: moonveil-backend-dev
    qcloud-app: moonveil-backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: moonveil-backend-dev
      qcloud-app: moonveil-backend-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: moonveil-backend-dev
        qcloud-app: moonveil-backend-dev
    spec:
      containers:
        - env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI
                  name: mongo
                  optional: false
            - name: MONGODB_URI_2048
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI_2048
                  name: mongo
                  optional: false
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  key: REDIS_URI
                  name: mongo
                  optional: false
            - name: MONGODB_DEV_URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DEV_URI
                  name: mongo
                  optional: false
            - name: TEST
              valueFrom:
                secretKeyRef:
                  key: TEST
                  name: mongo
                  optional: false
          image: moonveil-entertainment.tencentcloudcr.com/moonveil/moonveil-backend:${GITHUB_SHA}
          imagePullPolicy: Always
          name: moonveil-backend-dev
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 256Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: moonveil-image-pull
